#!/bin/bash
  
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

runApplication foamCleanPolyMesh
mv log.foamCleanPolyMesh log.foamCleanPolyMesh.gasPhase

rm -fr log*
rm -fr *.obj
rm -rf VTK
rm -rf patch*
rm -rf fieldMimMax  HRR  probes
rm -fr fieldMinMax
rm -fr postProcessing

