#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

runApplication foamCleanPolyMesh
mv log.foamCleanPolyMesh log.foamCleanPolyMesh.gasPhase
runApplication foamCleanPolyMesh -region fuelRegion
mv log.foamCleanPolyMesh log.foamCleanPolyMesh.fuel

rm -rf log.*
rm -fr *.obj
rm -rf VTK
rm -rf patch*
rm -rf fieldMimMax  HRR  probes
rm -fr fieldMinMax
rm -fr postProcessing
rm -rf 0/ph_rgh
rm -rf 0/ph_rgh.gz
rm -rf outFlameHeight_0
rm -rf reconstructed_fields
rm -rf **/**/polyMesh
rm system/decomposeParDict
rm system/topoSetDict
rm system/extrudeToRegionMeshDict

# -----------------------------------------------------------------------------
