#!/bin/bash

cd ${0%/*} || exit 1
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
cleanCase
rm -rf liquidFuelWrites sprinklerPostProcessing
rm -rf postProcessing
rm -rf processor*
rm -f log.* outFlameHeight* 
foamCleanPolyMesh
